# Generated by Django 4.2.7 on 2023-12-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
