# Generated by Django 4.2.7 on 2023-12-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_release_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='rating_between',
            field=models.IntegerField(default=None),
        ),
    ]
