# Generated by Django 4.2.7 on 2023-12-08 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_rating_between'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
