# Generated by Django 4.2.7 on 2023-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
