# Generated by Django 4.2.7 on 2023-12-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_alter_musician_instument_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='instument_type',
            new_name='instrument_type',
        ),
    ]
