# Generated by Django 4.2.7 on 2023-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instument_type',
            field=models.CharField(choices=[('rock', 'Rock'), ('metal', 'Metal'), ('classic', 'Classic')], max_length=50),
        ),
    ]
